# Generated by Django 4.2.7 on 2023-11-30 04:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostProperti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_properti', models.CharField(max_length=50)),
                ('deskripsi_properti', models.TextField()),
                ('foto_properti', models.ImageField(upload_to='')),
                ('kota_properti', models.CharField(max_length=50)),
                ('negara_properti', models.CharField(max_length=50)),
                ('kode_pos_properti', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
