# Generated by Django 4.2.7 on 2023-12-03 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_properti', '0002_alter_postproperti_foto_properti'),
        ('userData', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='daftarPost',
            field=models.ManyToManyField(blank=True, to='post_properti.postproperti'),
        ),
        migrations.AddField(
            model_name='userdata',
            name='postFavorit',
            field=models.ManyToManyField(blank=True, related_name='postFavorit', to='post_properti.postproperti'),
        ),
    ]
